name: Test
on:
  push:
    branches:
      - main
      - development
jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
          channel: 'stable'
          architecture: x64
      - run: touch .env
      - run: touch .env_dev
      - run: flutter pub get
      - run: flutter pub run build_runner build
      - run: flutter pub run easy_localization:generate --source-dir ./assets/i18n
      - run: flutter pub run easy_localization:generate --source-dir ./assets/i18n -f keys -o locale_keys.g.dart
      - run: flutter test --coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage/lcov.info