include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # avoid_print: false  # Uncomment to disable the `avoid_print` rule
    prefer_single_quotes: true
    always_use_package_imports: true

analyzer:  
  exclude: 
    - '**/*.mocks.dart'
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - '**/*.config.dart'
    - '**/*.injectable.dart'
  errors:
    # remove error in mock Object.==' ('bool Function(Object)') isn't a valid concrete implementation of xxx
    # invalid_implementation_override: ignore
    invalid_annotation_target: ignore
